window.VIOLET_CATALOG = {
  systems: {
    silver: {
      name: 'Violet Silver',
      type: 'Антибактериальные панели',
      short: 'Защитное антибактериальное покрытие для «чистых» и медицинских помещений.',
      foundations: ['ГКЛ', 'Кремнит', 'СМЛ'],
      fireClass: 'КМ-0 / КМ-1',
      purpose: 'Внутренняя отделка «чистых» помещений',
      coating: 'Акриловое покрытие + антибактериальный УФ-лак',
      production: 'ГКЛ и СМЛ — 20 дней · Кремнит — 25 дней',
      description: [
        'Violet Silver разработана для медицинских учреждений, лабораторий, пищевых производств и помещений с повышенными требованиями к стерильности.',
        'Гладкая поверхность сохраняет внешний вид при ежедневной обработке дезинфицирующими составами, устойчива к ультрафиолету, механическим и химическим воздействиям.',
      ],
      benefits: ['антибактериальный защитный слой', 'влажная уборка и регулярная дезинфекция', 'гладкая поверхность без сложного ухода'],
      useCases: ['операционные и процедурные', 'лаборатории', 'пищевые производства', 'школы и социальные объекты'],
      images: [
        'assets/images/products/silver-1.jpg',
        'assets/images/products/silver-2.jpg',
        'assets/images/products/silver-3.jpg',
      ],
      source: 'https://vio-let.ru/production/dekorativnye-stenovye-paneli/antibakterialnye-paneli/',
    },
    ng: {
      name: 'Violet НГ',
      type: 'Негорючие панели',
      short: 'Огнезащита стен и потолков с полноценным декоративным покрытием.',
      foundations: ['Кремнит', 'СМЛ'],
      fireClass: 'КМ-0',
      purpose: 'Внутренняя отделка стен и потолков',
      coating: 'Акриловое покрытие + защитный лак на водной основе',
      production: 'СМЛ — 5 дней · Кремнит — 10 дней',
      description: [
        'Violet НГ производится на негорючих основах и совмещает требования пожарной безопасности с готовой декоративной поверхностью.',
        'Панели устанавливаются сухим способом без предварительного выравнивания стен. Сборно-разборная система сохраняет доступ к коммуникациям и упрощает замену элементов.',
      ],
      benefits: ['класс пожарной опасности КМ-0', 'сухой и быстрый монтаж', '189 цветов лакокрасочного покрытия'],
      useCases: ['транспортные объекты', 'образовательные учреждения', 'общественные здания', 'помещения с повышенными требованиями к огнезащите'],
      images: [
        'assets/images/products/ng-1.jpg',
        'assets/images/products/ng-2.jpg',
        'assets/images/products/ng-3.jpg',
      ],
      source: 'https://vio-let.ru/production/dekorativnye-stenovye-paneli/negoryuchie-paneli/',
    },
    acoustic: {
      name: 'Violet Acoustic',
      type: 'Акустические панели',
      short: 'Перфорированная отделка для управления эхом и акустическим комфортом.',
      foundations: ['ГКЛ', 'Кремнит', 'МДФ', 'СМЛ'],
      fireClass: 'КМ-0 / КМ-1 / КМ-5',
      purpose: 'Внутренняя отделка и акустический комфорт',
      coating: 'Акрил, шпон или HPL — в зависимости от задачи',
      production: 'ГКЛ и МДФ — 15 дней · СМЛ — 20 дней',
      description: [
        'Violet Acoustic — перфорированные панели для стен и потолков, снижающие эхо и реверберацию в общественных и специализированных пространствах.',
        'Разные виды перфорации, основы и покрытий позволяют включить акустическое решение в общую концепцию интерьера, не превращая его в технический элемент.',
      ],
      benefits: ['контроль эха и реверберации', 'разные рисунки перфорации', 'окраска, шпон и HPL-покрытие'],
      useCases: ['актовые и концертные залы', 'студии звукозаписи', 'переговорные', 'школы, аэропорты и спортивные арены'],
      images: [
        'assets/images/products/acoustic-1.jpg',
        'assets/images/products/acoustic-2.jpg',
        'assets/images/products/acoustic-3.jpg',
      ],
      source: 'https://vio-let.ru/production/dekorativnye-stenovye-paneli/akusticheskie-paneli/',
    },
    organic: {
      name: 'Violet Organic',
      type: 'Шпонированные панели',
      short: 'Натуральная древесная фактура для представительских интерьеров.',
      foundations: ['ГСП', 'СМЛ'],
      fireClass: 'КМ-1',
      purpose: 'Премиальная внутренняя отделка',
      coating: 'Натуральный или реконструированный шпон + защитный лак',
      production: 'ГСП и СМЛ — 12 дней',
      description: [
        'Violet Organic сочетает технологичную основу с натуральным или реконструированным шпоном. Каждая панель сохраняет выразительную древесную фактуру.',
        'Открытая и скрытая системы монтажа позволяют собирать как бесшовные панно, так и ритмичную отделку с металлическими вставками.',
      ],
      benefits: ['натуральная фактура дерева', '177 вариантов шпонированного покрытия', 'возможность скрытого монтажа'],
      useCases: ['кабинеты руководителей', 'лобби и зоны отдыха', 'бутики и офисы высокого класса', 'частные интерьеры'],
      images: [
        'assets/images/products/organic-1.jpg',
        'assets/images/products/organic-2.jpg',
        'assets/images/products/organic-3.jpg',
      ],
      source: 'https://vio-let.ru/production/dekorativnye-stenovye-paneli/shponirovannye-paneli/',
    },
    protect: {
      name: 'Violet Protect',
      type: 'Панели с полимерным покрытием',
      short: 'Гладкая износостойкая поверхность для помещений с высокой нагрузкой.',
      foundations: ['ГКЛ', 'Кремнит', 'СМЛ'],
      fireClass: 'КМ-0 / КМ-1',
      purpose: 'Внутренняя отделка помещений',
      coating: 'Многослойное полимерное покрытие + защитный УФ-лак',
      production: 'ГКЛ и СМЛ — 10 дней · Кремнит — 12 дней',
      description: [
        'Violet Protect объединяет декоративную гладкую поверхность с повышенной стойкостью к износу, влажной уборке и перепадам влажности.',
        'Матовые и высокоглянцевые варианты подходят для зон с высокой проходимостью и помогают сократить расходы на последующие ремонтные работы.',
      ],
      benefits: ['матовое или высокоглянцевое исполнение', '189 цветов', 'повышенная стойкость к влажной уборке'],
      useCases: ['коридоры и входные группы', 'офисы и административные здания', 'медицинские учреждения', 'торговые пространства'],
      images: [
        'assets/images/products/protect-1.jpg',
        'assets/images/products/protect-2.jpg',
        'assets/images/products/protect-3.jpg',
      ],
      source: 'https://vio-let.ru/production/dekorativnye-stenovye-paneli/paneli-s-polimernym-pokrytiem/',
    },
    color: {
      name: 'Violet Color',
      type: 'Гипсоакриловые панели',
      short: 'Рациональная готовая отделка для офисных и общественных интерьеров.',
      foundations: ['ГКЛ', 'ГСП'],
      fireClass: 'КМ-1',
      purpose: 'Быстрая внутренняя отделка помещений',
      coating: 'Акриловое покрытие + защитный лак на водной основе',
      production: 'ГКЛ — 5 дней · ГСП — 10 дней',
      description: [
        'Violet Color — готовые гипсоакриловые панели с заводским многослойным покрытием. Они устанавливаются без мокрых процессов и длительной подготовки стен.',
        'Решение рассчитано на качественную и экономичную отделку офисных, муниципальных и административных интерьеров.',
      ],
      benefits: ['189 цветов лакокрасочного покрытия', 'сухой монтаж без сложной подготовки', 'сборно-разборная конструкция'],
      useCases: ['офисы и переговорные', 'муниципальные учреждения', 'кабинеты и коридоры', 'зонирующие перегородки'],
      images: [
        'assets/images/products/color-1.jpg',
        'assets/images/products/color-2.jpg',
        'assets/images/products/color-3.jpg',
      ],
      source: 'https://vio-let.ru/production/dekorativnye-stenovye-paneli/gipsoakrilovye-paneli/',
    },
    basis: {
      name: 'Violet Basis', type: 'Базовые негорючие панели',
      short: 'Негорючая базовая облицовка под финишную отделку и инженерные задачи.',
      foundations: ['Кремнит', 'СМЛ'], fireClass: 'КМ-0', purpose: 'Прочное основание и огнезащита',
      coating: 'Акриловое покрытие + защитный лак на водной основе', production: 'СМЛ — 5 дней · Кремнит — 10 дней',
      description: ['Violet Basis — базовая панель для проектов, где важны негорючее основание, стабильная геометрия и быстрый сухой монтаж.', 'Ее используют как самостоятельную облицовку или основу для финишного декоративного решения.'],
      benefits: ['класс пожарной опасности КМ-0', 'сухой монтаж без мокрых процессов', 'удобная замена отдельных элементов'],
      useCases: ['коридоры и холлы', 'технические и общественные зоны', 'транспортные объекты', 'помещения с требованиями к огнезащите'],
      images: ['assets/images/products/ng-1.jpg','assets/images/products/ng-2.jpg','assets/images/products/ng-3.jpg'],
      source: 'https://vio-let.ru/production/dekorativnye-stenovye-paneli/negoryuchie-paneli/',
    },
    medium: {
      name: 'Violet Medium', type: 'Древесноволокнистые панели',
      short: 'Древесноволокнистая основа для быстрой внутренней отделки.', foundations: ['ГКЛ', 'ГСП'], fireClass: 'КМ-2',
      purpose: 'Внутренняя отделка помещений', coating: 'Акриловое покрытие + защитный лак на водной основе', production: '10 дней',
      description: ['Violet Medium сочетает древесноволокнистую основу с готовым декоративным покрытием и сухим монтажом.', '189 цветов помогают собрать спокойный фон или акцентную стену без мокрых процессов.'],
      benefits: ['189 цветов покрытия', 'быстрый сухой монтаж', 'экономичная внутренняя отделка'], useCases: ['офисы', 'коридоры', 'школы', 'бытовые и общественные помещения'],
      images: ['assets/images/products/medium/01.jpg','assets/images/products/medium/02.jpg','assets/images/products/medium/03.jpg'],
      source: 'https://vio-let.ru/production/dekorativnye-stenovye-paneli/drevesnovoloknistye-paneli/',
    },
    sky: {
      name: 'Violet Sky', type: 'Потолочные панели', short: 'Цветная отделка подвесных потолков с понятной сборной системой.', foundations: ['ГКЛ', 'Кремнит', 'СМЛ'], fireClass: 'КМ-0 / КМ-1',
      purpose: 'Отделка подвесных потолков', coating: 'Акриловое покрытие + защитный УФ-лак', production: 'ГКЛ, СМЛ, Кремнит — 10 дней',
      description: ['Violet Sky предназначена для декоративной отделки подвесных потолков в общественных и коммерческих зданиях.', 'Панели выпускаются в 189 цветах и сохраняют доступ к инженерным коммуникациям.'],
      benefits: ['189 цветов', 'огнезащита потолка', 'быстрый монтаж'], useCases: ['офисы', 'коридоры и холлы', 'учебные помещения', 'общественные здания'],
      images: ['assets/images/products/sky/01.jpg','assets/images/products/sky/02.jpg','assets/images/products/sky/03.jpg'], source: 'https://vio-let.ru/production/dekorativnye-stenovye-paneli/potolki/',
    },
    vinyl: {
      name: 'Violet Vinyl', type: 'Гипсовиниловые панели', short: 'Износостойкая виниловая отделка для интенсивно используемых интерьеров.', foundations: ['ГКЛ', 'Кремнит', 'МДФ', 'СМЛ'], fireClass: 'КМ-1', purpose: 'Внутренняя отделка помещений', coating: 'Виниловые обои Durafort', production: 'ГКЛ, СМЛ — 10 дней',
      description: ['Violet Vinyl — гипсовиниловая панель с фактурой Durafort и готовой поверхностью.', 'Решение подходит для сухого монтажа и регулярной эксплуатации в общественных зонах.'], benefits: ['47 цветов винилового покрытия', 'износостойкая поверхность', 'быстрый сухой монтаж'], useCases: ['офисы', 'гостиницы', 'торговые помещения', 'общественные зоны'],
      images: ['assets/images/products/vinyl/01.jpg','assets/images/products/vinyl/02.jpg','assets/images/products/vinyl/03.jpg'], source: 'https://vio-let.ru/production/dekorativnye-stenovye-paneli/gipsovinilovye-paneli/',
    },
    sticker: {
      name: 'Violet Sticker', type: 'Ламинированные стеновые панели', short: 'Прочная ПВХ-плёнка и широкий выбор декоров для ежедневной эксплуатации.', foundations: ['ГВЛ', 'ГКЛ', 'ГСП', 'Кремнит', 'МДФ', 'СМЛ'], fireClass: 'КМ-1', purpose: 'Внутренняя отделка помещений', coating: 'Высокопрочная поливинилхлоридная плёнка', production: 'ГКЛ, СМЛ — 8 дней · ГВЛ, ГСП — 12 дней',
      description: ['Violet Sticker — ламинированные панели с высокопрочной ПВХ-плёнкой и 87 цветами и декорами.', 'Сборно-разборная конструкция упрощает обслуживание и частичную замену листов.'], benefits: ['87 цветов и декоров', 'износостойкая поверхность', 'сборно-разборный монтаж'], useCases: ['офисы', 'банкетные залы', 'спортзалы', 'кинотеатры'],
      images: ['assets/images/products/sticker/01.jpg','assets/images/products/sticker/02.jpg','assets/images/products/sticker/03.jpg'], source: 'https://vio-let.ru/production/dekorativnye-stenovye-paneli/laminirovannye-paneli/',
    },
    plastic: {
      name: 'Violet Plastic', type: 'Антивандальные панели', short: 'HPL-поверхность для помещений с повышенной нагрузкой и риском повреждений.', foundations: ['ГВЛ', 'ГСП', 'СМЛ'], fireClass: 'КМ-0 / КМ-1', purpose: 'Внутренняя отделка помещений', coating: 'Пластик высокого давления HPL', production: 'СМЛ, ГСП, ГВЛ — 20 дней · HPL — 15 дней',
      description: ['Violet Plastic рассчитана на интенсивную эксплуатацию: HPL-покрытие устойчиво к истиранию, ударам и регулярной уборке.', '268 декоров помогают подобрать решение для транспорта, медицины и образования.'], benefits: ['268 декоров HPL', 'устойчивость к истиранию и ударам', 'частичная замена листов'], useCases: ['больницы', 'школы', 'спортзалы', 'транспортные объекты'],
      images: ['assets/images/products/plastic/01.jpg','assets/images/products/plastic/02.jpg','assets/images/products/plastic/03.jpg'], source: 'https://vio-let.ru/production/dekorativnye-stenovye-paneli/antivandalnye-paneli/',
    },
    front: {
      name: 'Violet Front', type: 'Фасадные панели', short: 'Фасадная система для наружной отделки, входных групп и цоколей.', foundations: ['ФЦП', 'Кремнит', 'HPL'], fireClass: 'КМ-0 / КМ-1', purpose: 'Наружная отделка зданий', coating: 'УФ-стойкое акриловое покрытие или HPL', production: 'По проектной спецификации',
      description: ['Violet Front переносит фирменную эстетику VIOLET на фасад: панели применяются для наружной отделки, цоколей и входных групп.', 'Варианты на ФЦП, Кремните и HPL подбираются под требования объекта и узлы крепления.'], benefits: ['фасады и цоколи', 'широкая гамма декоров', 'универсальные варианты креплений'], useCases: ['общественные здания', 'коммерческие объекты', 'административные здания', 'фасады и входные группы'],
      images: ['assets/images/products/front/01.jpg','assets/images/products/front/02.jpg','assets/images/products/front/03.jpg'], source: 'https://vio-let.ru/production/fasadnye-paneli/',
    },
  },
  projects: [
    {
      id: 'gimnaziya-imeni-e-m-primakova',
      title: 'Гимназия имени Е. М. Примакова',
      category: 'education',
      categoryLabel: 'Образование',
      location: 'Московская область',
      panels: 'Антивандальные панели',
      foundation: 'По проектной спецификации',
      coating: 'Слоистый пластик высокого давления HPL',
      volume: 'Комплексная отделка стен и потолков',
      term: 'Проектная поставка',
      description: 'Комплексная отделка учебных, общественных и творческих пространств износостойкими панелями с HPL-покрытием.',
      images: [1, 2, 3, 4].map((number) => `assets/images/projects/gimnaziya-imeni-e-m-primakova/0${number}.jpg`),
      source: 'https://vio-let.ru/portfolio/gimnaziya-imeni-e-m-primakova/',
    },
    {
      id: 'stantsiya-metro-begovaya',
      title: 'Станция метро «Беговая»',
      category: 'infrastructure',
      categoryLabel: 'Транспорт',
      location: 'Санкт-Петербург',
      panels: 'Панели с полимерным покрытием',
      foundation: 'СМЛ',
      coating: 'Лакокрасочное покрытие',
      volume: '1 035 м²',
      term: '15 дней',
      description: 'Полимерные панели на основе СМЛ для интенсивно эксплуатируемого транспортного объекта; поставка 1 035 м² за 15 дней.',
      images: [1, 2, 3, 4].map((number) => `assets/images/projects/stantsiya-metro-begovaya/0${number}.jpg`),
      source: 'https://vio-let.ru/portfolio/stantsiya-metro-begovaya/',
    },
    {
      id: 'aeroport-g-nadym',
      title: 'Аэропорт Надым',
      category: 'infrastructure',
      categoryLabel: 'Транспорт',
      location: 'Надым',
      panels: 'Негорючие и фасадные панели',
      foundation: 'СМЛ',
      coating: 'Лакокрасочное покрытие',
      volume: '400 м²',
      term: '7 дней',
      description: 'Негорючие и фасадные панели на основе СМЛ для аэропортового комплекса; 400 м², срок выполнения 7 дней.',
      images: [1, 2, 3, 4].map((number) => `assets/images/projects/aeroport-g-nadym/0${number}.jpg`),
      source: 'https://vio-let.ru/portfolio/aeroport-g-nadym/',
    },
    {
      id: 'dk-sovremennik',
      title: 'ДК «Современник»',
      category: 'culture',
      categoryLabel: 'Культура',
      location: 'Россия',
      panels: 'Акустические и полимерные панели',
      foundation: 'СМЛ',
      coating: 'Лакокрасочное покрытие',
      volume: '1 500 м²',
      term: '3 недели',
      description: 'Акустические и полимерные панели на основе СМЛ для культурного пространства; поставка 1 500 м².',
      images: [1, 2, 3, 4].map((number) => `assets/images/projects/dk-sovremennik/0${number}.jpg`),
      source: 'https://vio-let.ru/portfolio/dk-sovremennik/',
    },
    {
      id: 'sportivno-razvlekatelnyy-kompleks-galaktika',
      title: 'СКК «Галактика»',
      category: 'sport',
      categoryLabel: 'Спорт',
      location: 'Когалым',
      panels: 'Антивандальные панели',
      foundation: 'СМЛ',
      coating: 'Слоистый пластик HPL',
      volume: '3 850 м²',
      term: '10 недель',
      description: 'Антивандальная отделка на основе СМЛ с HPL-покрытием для спортивно-развлекательного комплекса; 3 850 м².',
      images: [1, 2, 3, 4].map((number) => `assets/images/projects/sportivno-razvlekatelnyy-kompleks-galaktika/0${number}.jpg`),
      source: 'https://vio-let.ru/portfolio/sportivno-razvlekatelnyy-kompleks-galaktika/',
    },
    {
      id: 'park-inn-by-radisson-nevsky',
      title: 'Park Inn by Radisson Nevsky',
      category: 'hospitality',
      categoryLabel: 'HoReCa',
      location: 'Санкт-Петербург',
      panels: 'Антивандальные панели',
      foundation: 'СМЛ',
      coating: 'Слоистый пластик HPL',
      volume: '100 м²',
      term: '15 дней',
      description: 'Антивандальные HPL-панели на основе СМЛ для гостиничного интерьера; 100 м² за 15 дней.',
      images: [1, 2, 3, 4].map((number) => `assets/images/projects/park-inn-by-radisson-nevsky/0${number}.jpg`),
      source: 'https://vio-let.ru/portfolio/park-inn-by-radisson-nevsky/',
    },
    {
      id: 'klinika-neva',
      title: 'Клиника «Нева»',
      category: 'medical',
      categoryLabel: 'Медицина',
      location: 'Ульяновск',
      panels: 'Антивандальные и гипсовиниловые панели',
      foundation: 'СМЛ',
      coating: 'Слоистый пластик HPL',
      volume: '41 м²',
      term: '12 дней',
      description: 'Антивандальные и гипсовиниловые панели на основе СМЛ для клиники в Ульяновске; 41 м² за 12 дней.',
      images: [1, 2, 3, 4].map((number) => `assets/images/projects/klinika-neva/0${number}.jpg`),
      source: 'https://vio-let.ru/portfolio/klinika-neva/',
    },
    {
      id: 'mnogofunktsionalnyy-voennyy-gospital-ministerstva-oborony',
      title: 'Военный госпиталь Минобороны',
      category: 'special',
      categoryLabel: 'Специальные объекты',
      location: 'Россия',
      panels: 'Панели с полимерным покрытием',
      foundation: 'СМЛ',
      coating: 'Лакокрасочное покрытие',
      volume: '15 000 м²',
      term: '10 дней',
      description: 'Полимерные панели на основе СМЛ для многофункционального госпиталя; поставка 15 000 м² за 10 дней.',
      images: [1, 2, 3, 4].map((number) => `assets/images/projects/mnogofunktsionalnyy-voennyy-gospital-ministerstva-oborony/0${number}.jpg`),
      source: 'https://vio-let.ru/portfolio/mnogofunktsionalnyy-voennyy-gospital-ministerstva-oborony/',
    },
    {
      id: 'fiziko-energeticheskij-institut-imeni-a-i-lejpunskogo',
      title: 'Физико-Энергетический институт имени А. И. Лейпунского', category: 'industrial', categoryLabel: 'Исследовательский объект', location: 'Обнинск, Калужская область',
      panels: 'Антивандальные панели', foundation: 'ГСП', coating: 'Износостойкое покрытие', volume: 'Комплексная отделка', term: 'Проектная поставка',
      description: 'Антивандальные панели на основе ГСП для помещений с высокой проходимостью и требованиями к износостойкости.',
      images: [1, 2, 3, 4].map((number) => `assets/images/projects/fiziko-energeticheskij-institut-imeni-a-i-lejpunskogo/0${number}.jpg`), source: 'https://vio-let.ru/portfolio/fiziko-energeticheskij-institut-imeni-a-i-lejpunskogo/',
    },
    {
      id: 'myasopererabatyvayushhij-kombinat-privolzhskie-kolbasy',
      title: 'Мясоперерабатывающий комбинат «Приволжские колбасы»', category: 'industrial', categoryLabel: 'Промышленность', location: 'Новочебоксарск, Чувашия',
      panels: 'Ламинированные панели', foundation: 'По проектной спецификации', coating: 'Поливинилхлоридная плёнка', volume: 'Производственные и административные помещения', term: 'Проектная поставка',
      description: 'Ламинированные панели с ПВХ-плёнкой для производственного объекта в Новочебоксарске.',
      images: [1, 2, 3, 4].map((number) => `assets/images/projects/myasopererabatyvayushhij-kombinat-privolzhskie-kolbasy/0${number}.jpg`), source: 'https://vio-let.ru/portfolio/myasopererabatyvayushhij-kombinat-privolzhskie-kolbasy/',
    },
  ],
};
